-- Generated from app/_content/antique-barangays.ts. Do not edit by hand.

insert into public.municipalities (name, province, psgc_code)
values
  ('Anini-y', 'Antique', '0600601000'),
  ('Barbaza', 'Antique', '0600602000'),
  ('Belison', 'Antique', '0600603000'),
  ('Bugasong', 'Antique', '0600604000'),
  ('Caluya', 'Antique', '0600605000'),
  ('Culasi', 'Antique', '0600606000'),
  ('Tobias Fornier', 'Antique', '0600607000'),
  ('Hamtic', 'Antique', '0600608000'),
  ('Laua-an', 'Antique', '0600609000'),
  ('Libertad', 'Antique', '0600610000'),
  ('Pandan', 'Antique', '0600611000'),
  ('Patnongon', 'Antique', '0600612000'),
  ('San Jose de Buenavista', 'Antique', '0600613000'),
  ('San Remigio', 'Antique', '0600614000'),
  ('Sebaste', 'Antique', '0600615000'),
  ('Sibalom', 'Antique', '0600616000'),
  ('Tibiao', 'Antique', '0600617000'),
  ('Valderrama', 'Antique', '0600618000')
on conflict (name) do update set
  province = excluded.province,
  psgc_code = excluded.psgc_code;

insert into public.barangays (municipality_id, name)
select municipalities.id, values_to_insert.name
from (values
  ('Anini-y', 'Bayo Grande'),
  ('Anini-y', 'Bayo Pequeño'),
  ('Anini-y', 'Butuan'),
  ('Anini-y', 'Casay'),
  ('Anini-y', 'Casay Viejo'),
  ('Anini-y', 'Iba'),
  ('Anini-y', 'Igbarabatuan'),
  ('Anini-y', 'Igpalge'),
  ('Anini-y', 'Igtumarom'),
  ('Anini-y', 'Lisub A'),
  ('Anini-y', 'Lisub B'),
  ('Anini-y', 'Mabuyong'),
  ('Anini-y', 'Magdalena'),
  ('Anini-y', 'Nasuli C'),
  ('Anini-y', 'Nato'),
  ('Anini-y', 'Poblacion'),
  ('Anini-y', 'Sagua'),
  ('Anini-y', 'Salvacion'),
  ('Anini-y', 'San Francisco'),
  ('Anini-y', 'San Ramon'),
  ('Anini-y', 'San Roque'),
  ('Anini-y', 'Tagaytay'),
  ('Anini-y', 'Talisayan'),
  ('Barbaza', 'Baghari'),
  ('Barbaza', 'Bahuyan'),
  ('Barbaza', 'Beri'),
  ('Barbaza', 'Biga-a'),
  ('Barbaza', 'Binangbang'),
  ('Barbaza', 'Binangbang Centro'),
  ('Barbaza', 'Binanu-an'),
  ('Barbaza', 'Cadiao'),
  ('Barbaza', 'Calapadan'),
  ('Barbaza', 'Capoyuan'),
  ('Barbaza', 'Cubay'),
  ('Barbaza', 'Esparar'),
  ('Barbaza', 'Gua'),
  ('Barbaza', 'Idao'),
  ('Barbaza', 'Igpalge'),
  ('Barbaza', 'Igtunarum'),
  ('Barbaza', 'Embrangga-an'),
  ('Barbaza', 'Integasan'),
  ('Barbaza', 'Ipil'),
  ('Barbaza', 'Jinalinan'),
  ('Barbaza', 'Lanas'),
  ('Barbaza', 'Langcaon'),
  ('Barbaza', 'Lisub'),
  ('Barbaza', 'Lombuyan'),
  ('Barbaza', 'Mablad'),
  ('Barbaza', 'Magtulis'),
  ('Barbaza', 'Marigne'),
  ('Barbaza', 'Mayabay'),
  ('Barbaza', 'Mayos'),
  ('Barbaza', 'Nalusdan'),
  ('Barbaza', 'Narirong'),
  ('Barbaza', 'Palma'),
  ('Barbaza', 'Poblacion'),
  ('Barbaza', 'San Antonio'),
  ('Barbaza', 'San Ramon'),
  ('Barbaza', 'Soligao'),
  ('Barbaza', 'Tabongtabong'),
  ('Barbaza', 'Tig-Alaran'),
  ('Barbaza', 'Yapo'),
  ('Belison', 'Borocboroc'),
  ('Belison', 'Buenavista'),
  ('Belison', 'Concepcion'),
  ('Belison', 'Delima'),
  ('Belison', 'Ipil'),
  ('Belison', 'Maradiona'),
  ('Belison', 'Mojon'),
  ('Belison', 'Poblacion'),
  ('Belison', 'Rombang'),
  ('Belison', 'Salvacion'),
  ('Belison', 'Sinaja'),
  ('Bugasong', 'Anilawan'),
  ('Bugasong', 'Arangote'),
  ('Bugasong', 'Bagtason'),
  ('Bugasong', 'Camangahan'),
  ('Bugasong', 'Cubay North'),
  ('Bugasong', 'Cubay South'),
  ('Bugasong', 'Guija'),
  ('Bugasong', 'Igbalangao'),
  ('Bugasong', 'Igsoro'),
  ('Bugasong', 'Ilaures'),
  ('Bugasong', 'Jinalinan'),
  ('Bugasong', 'Lacayon'),
  ('Bugasong', 'Maray'),
  ('Bugasong', 'Paliwan'),
  ('Bugasong', 'Pangalcagan'),
  ('Bugasong', 'Centro Ilawod'),
  ('Bugasong', 'Centro Ilaya'),
  ('Bugasong', 'Centro Pojo'),
  ('Bugasong', 'Sabang East'),
  ('Bugasong', 'Sabang West'),
  ('Bugasong', 'Tagudtud North'),
  ('Bugasong', 'Tagudtud South'),
  ('Bugasong', 'Talisay'),
  ('Bugasong', 'Tica'),
  ('Bugasong', 'Tono-an'),
  ('Bugasong', 'Yapu'),
  ('Bugasong', 'Zaragoza'),
  ('Caluya', 'Alegria'),
  ('Caluya', 'Bacong'),
  ('Caluya', 'Banago'),
  ('Caluya', 'Bonbon'),
  ('Caluya', 'Dawis'),
  ('Caluya', 'Dionela'),
  ('Caluya', 'Harigue'),
  ('Caluya', 'Hininga-an'),
  ('Caluya', 'Imba'),
  ('Caluya', 'Masanag'),
  ('Caluya', 'Poblacion'),
  ('Caluya', 'Sabang'),
  ('Caluya', 'Salamento'),
  ('Caluya', 'Semirara'),
  ('Caluya', 'Sibato'),
  ('Caluya', 'Sibay'),
  ('Caluya', 'Sibolo'),
  ('Caluya', 'Tinogboc'),
  ('Culasi', 'Alojipan'),
  ('Culasi', 'Bagacay'),
  ('Culasi', 'Balac-balac'),
  ('Culasi', 'Magsaysay'),
  ('Culasi', 'Batbatan Island'),
  ('Culasi', 'Batonan Norte'),
  ('Culasi', 'Batonan Sur'),
  ('Culasi', 'Bita'),
  ('Culasi', 'Bitadton Norte'),
  ('Culasi', 'Bitadton Sur'),
  ('Culasi', 'Buenavista'),
  ('Culasi', 'Buhi'),
  ('Culasi', 'Camancijan'),
  ('Culasi', 'Caridad'),
  ('Culasi', 'Carit-an'),
  ('Culasi', 'Condes'),
  ('Culasi', 'Esperanza'),
  ('Culasi', 'Fe'),
  ('Culasi', 'Flores'),
  ('Culasi', 'Jalandoni'),
  ('Culasi', 'Janlagasi'),
  ('Culasi', 'Lamputong'),
  ('Culasi', 'Lipata'),
  ('Culasi', 'Malacañang'),
  ('Culasi', 'Malalison Island'),
  ('Culasi', 'Maniguin'),
  ('Culasi', 'Naba'),
  ('Culasi', 'Osorio'),
  ('Culasi', 'Paningayan'),
  ('Culasi', 'Centro Poblacion'),
  ('Culasi', 'Centro Norte'),
  ('Culasi', 'Centro Sur'),
  ('Culasi', 'Salde'),
  ('Culasi', 'San Antonio'),
  ('Culasi', 'San Gregorio'),
  ('Culasi', 'San Juan'),
  ('Culasi', 'San Luis'),
  ('Culasi', 'San Pascual'),
  ('Culasi', 'San Vicente'),
  ('Culasi', 'Simbola'),
  ('Culasi', 'Tigbobolo'),
  ('Culasi', 'Tinabusan'),
  ('Culasi', 'Tomao'),
  ('Culasi', 'Valderama'),
  ('Tobias Fornier', 'Abaca'),
  ('Tobias Fornier', 'Aras-Asan'),
  ('Tobias Fornier', 'Arobo'),
  ('Tobias Fornier', 'Atabay'),
  ('Tobias Fornier', 'Atiotes'),
  ('Tobias Fornier', 'Bagumbayan'),
  ('Tobias Fornier', 'Balloscas'),
  ('Tobias Fornier', 'Balud'),
  ('Tobias Fornier', 'Barasanan A'),
  ('Tobias Fornier', 'Barasanan B'),
  ('Tobias Fornier', 'Barasanan C'),
  ('Tobias Fornier', 'Bariri'),
  ('Tobias Fornier', 'Camandagan'),
  ('Tobias Fornier', 'Cato-ogan'),
  ('Tobias Fornier', 'Danawan'),
  ('Tobias Fornier', 'Diclum'),
  ('Tobias Fornier', 'Fatima'),
  ('Tobias Fornier', 'Gamad'),
  ('Tobias Fornier', 'Igbalogo'),
  ('Tobias Fornier', 'Igbangcal-A'),
  ('Tobias Fornier', 'Igbangcal-B'),
  ('Tobias Fornier', 'Igbangcal-C'),
  ('Tobias Fornier', 'Igcabuad'),
  ('Tobias Fornier', 'Igcado'),
  ('Tobias Fornier', 'Igcalawagan'),
  ('Tobias Fornier', 'Igcapuyas'),
  ('Tobias Fornier', 'Igcasicad'),
  ('Tobias Fornier', 'Igdalaguit'),
  ('Tobias Fornier', 'Igdanlog'),
  ('Tobias Fornier', 'Igdurarog'),
  ('Tobias Fornier', 'Igtugas'),
  ('Tobias Fornier', 'Lawigan'),
  ('Tobias Fornier', 'Manaling'),
  ('Tobias Fornier', 'Masayo'),
  ('Tobias Fornier', 'Nagsubuan'),
  ('Tobias Fornier', 'Paciencia'),
  ('Tobias Fornier', 'Poblacion Norte'),
  ('Tobias Fornier', 'Poblacion Sur'),
  ('Tobias Fornier', 'Portillo'),
  ('Tobias Fornier', 'Quezon'),
  ('Tobias Fornier', 'Opsan'),
  ('Tobias Fornier', 'Nasuli-A'),
  ('Tobias Fornier', 'Salamague'),
  ('Tobias Fornier', 'Santo Tomas'),
  ('Tobias Fornier', 'Tacbuyan'),
  ('Tobias Fornier', 'Tene'),
  ('Tobias Fornier', 'Villaflor'),
  ('Tobias Fornier', 'Ysulat'),
  ('Tobias Fornier', 'Igcadac'),
  ('Tobias Fornier', 'Lindero'),
  ('Hamtic', 'Apdo'),
  ('Hamtic', 'Asluman'),
  ('Hamtic', 'Banawon'),
  ('Hamtic', 'Bia-an'),
  ('Hamtic', 'Bongbongan I-II'),
  ('Hamtic', 'Bongbongan III'),
  ('Hamtic', 'Botbot'),
  ('Hamtic', 'Budbudan'),
  ('Hamtic', 'Buhang'),
  ('Hamtic', 'Calacja I'),
  ('Hamtic', 'Calacja II'),
  ('Hamtic', 'Calala'),
  ('Hamtic', 'Cantulan'),
  ('Hamtic', 'Caridad'),
  ('Hamtic', 'Caromangay'),
  ('Hamtic', 'Casalngan'),
  ('Hamtic', 'Dangcalan'),
  ('Hamtic', 'Del Pilar'),
  ('Hamtic', 'Fabrica'),
  ('Hamtic', 'Funda'),
  ('Hamtic', 'General Fullon'),
  ('Hamtic', 'Guintas'),
  ('Hamtic', 'Igbical'),
  ('Hamtic', 'Igbucagay'),
  ('Hamtic', 'Inabasan'),
  ('Hamtic', 'Ingwan-Batangan'),
  ('Hamtic', 'La Paz'),
  ('Hamtic', 'Gov. Evelio B. Javier'),
  ('Hamtic', 'Linaban'),
  ('Hamtic', 'Malandog'),
  ('Hamtic', 'Mapatag'),
  ('Hamtic', 'Masanag'),
  ('Hamtic', 'Nalihawan'),
  ('Hamtic', 'Pamandayan'),
  ('Hamtic', 'Pasu-Jungao'),
  ('Hamtic', 'Piapi I'),
  ('Hamtic', 'Piapi II'),
  ('Hamtic', 'Piapi III'),
  ('Hamtic', 'Pili 1, 2, 3'),
  ('Hamtic', 'Poblacion 1'),
  ('Hamtic', 'Poblacion 2'),
  ('Hamtic', 'Poblacion 3'),
  ('Hamtic', 'Poblacion 4'),
  ('Hamtic', 'Poblacion 5'),
  ('Hamtic', 'Pu-ao'),
  ('Hamtic', 'Suloc'),
  ('Hamtic', 'Villavert-Jimenez'),
  ('Laua-an', 'Banban'),
  ('Laua-an', 'Bongbongan'),
  ('Laua-an', 'Cabariwan'),
  ('Laua-an', 'Cadajug'),
  ('Laua-an', 'Canituan'),
  ('Laua-an', 'Capnayan'),
  ('Laua-an', 'Casit-an'),
  ('Laua-an', 'Guinbanga-an'),
  ('Laua-an', 'Guiamon'),
  ('Laua-an', 'Guisijan'),
  ('Laua-an', 'Igtadiao'),
  ('Laua-an', 'Intao'),
  ('Laua-an', 'Jaguikican'),
  ('Laua-an', 'Jinalinan'),
  ('Laua-an', 'Lactudan'),
  ('Laua-an', 'Latazon'),
  ('Laua-an', 'Laua-an'),
  ('Laua-an', 'Leon'),
  ('Laua-an', 'Liberato'),
  ('Laua-an', 'Lindero'),
  ('Laua-an', 'Liya-liya'),
  ('Laua-an', 'Lugta'),
  ('Laua-an', 'Lupa-an'),
  ('Laua-an', 'Magyapo'),
  ('Laua-an', 'Maria'),
  ('Laua-an', 'Mauno'),
  ('Laua-an', 'Maybunga'),
  ('Laua-an', 'Necesito'),
  ('Laua-an', 'Oloc'),
  ('Laua-an', 'Omlot'),
  ('Laua-an', 'Pandanan'),
  ('Laua-an', 'Paningayan'),
  ('Laua-an', 'Pascuala'),
  ('Laua-an', 'Poblacion'),
  ('Laua-an', 'San Ramon'),
  ('Laua-an', 'Santiago'),
  ('Laua-an', 'Tibacan'),
  ('Laua-an', 'Tigunhao'),
  ('Laua-an', 'Virginia'),
  ('Laua-an', 'Bagongbayan'),
  ('Libertad', 'Barusbus'),
  ('Libertad', 'Bulanao'),
  ('Libertad', 'Cubay'),
  ('Libertad', 'Codiong'),
  ('Libertad', 'Igcagay'),
  ('Libertad', 'Inyawan'),
  ('Libertad', 'Lindero'),
  ('Libertad', 'Maramig'),
  ('Libertad', 'Pucio'),
  ('Libertad', 'Pajo'),
  ('Libertad', 'Panangkilon'),
  ('Libertad', 'Paz'),
  ('Libertad', 'Centro Este'),
  ('Libertad', 'Centro Weste'),
  ('Libertad', 'San Roque'),
  ('Libertad', 'Tinigbas'),
  ('Libertad', 'Tinindugan'),
  ('Libertad', 'Taboc'),
  ('Libertad', 'Union'),
  ('Pandan', 'Aracay'),
  ('Pandan', 'Badiangan'),
  ('Pandan', 'Bagumbayan'),
  ('Pandan', 'Baybay'),
  ('Pandan', 'Botbot'),
  ('Pandan', 'Buang'),
  ('Pandan', 'Cabugao'),
  ('Pandan', 'Candari'),
  ('Pandan', 'Carmen'),
  ('Pandan', 'Centro Sur'),
  ('Pandan', 'Dionela'),
  ('Pandan', 'Dumrog'),
  ('Pandan', 'Duyong'),
  ('Pandan', 'Fragante'),
  ('Pandan', 'Guia'),
  ('Pandan', 'Idiacacan'),
  ('Pandan', 'Jinalinan'),
  ('Pandan', 'Luhod-Bayang'),
  ('Pandan', 'Maadios'),
  ('Pandan', 'Mag-aba'),
  ('Pandan', 'Napuid'),
  ('Pandan', 'Nauring'),
  ('Pandan', 'Patria'),
  ('Pandan', 'Perfecta'),
  ('Pandan', 'Centro Norte'),
  ('Pandan', 'San Andres'),
  ('Pandan', 'San Joaquin'),
  ('Pandan', 'Santa Ana'),
  ('Pandan', 'Santa Cruz'),
  ('Pandan', 'Santa Fe'),
  ('Pandan', 'Santo Rosario'),
  ('Pandan', 'Talisay'),
  ('Pandan', 'Tingib'),
  ('Pandan', 'Zaldivar'),
  ('Patnongon', 'Alvañiz'),
  ('Patnongon', 'Amparo'),
  ('Patnongon', 'Apgahan'),
  ('Patnongon', 'Aureliana'),
  ('Patnongon', 'Badiangan'),
  ('Patnongon', 'Bernaldo A. Julagting'),
  ('Patnongon', 'Carit-an'),
  ('Patnongon', 'Cuyapiao'),
  ('Patnongon', 'Villa Elio'),
  ('Patnongon', 'Gella'),
  ('Patnongon', 'Igbarawan'),
  ('Patnongon', 'Igbobon'),
  ('Patnongon', 'Igburi'),
  ('Patnongon', 'La Rioja'),
  ('Patnongon', 'Mabasa'),
  ('Patnongon', 'Macarina'),
  ('Patnongon', 'Magarang'),
  ('Patnongon', 'Magsaysay'),
  ('Patnongon', 'Padang'),
  ('Patnongon', 'Pandanan'),
  ('Patnongon', 'Patlabawon'),
  ('Patnongon', 'Poblacion'),
  ('Patnongon', 'Quezon'),
  ('Patnongon', 'Salaguiawan'),
  ('Patnongon', 'Samalague'),
  ('Patnongon', 'San Rafael'),
  ('Patnongon', 'Tobias Fornier'),
  ('Patnongon', 'Tamayoc'),
  ('Patnongon', 'Tigbalogo'),
  ('Patnongon', 'Villa Crespo'),
  ('Patnongon', 'Villa Cruz'),
  ('Patnongon', 'Villa Flores'),
  ('Patnongon', 'Villa Laua-an'),
  ('Patnongon', 'Villa Sal'),
  ('Patnongon', 'Villa Salomon'),
  ('Patnongon', 'Vista Alegre'),
  ('San Jose de Buenavista', 'Atabay'),
  ('San Jose de Buenavista', 'Badiang'),
  ('San Jose de Buenavista', 'Barangay 1'),
  ('San Jose de Buenavista', 'Barangay 2'),
  ('San Jose de Buenavista', 'Barangay 3'),
  ('San Jose de Buenavista', 'Barangay 4'),
  ('San Jose de Buenavista', 'Barangay 5'),
  ('San Jose de Buenavista', 'Barangay 6'),
  ('San Jose de Buenavista', 'Barangay 7'),
  ('San Jose de Buenavista', 'Barangay 8'),
  ('San Jose de Buenavista', 'Bariri'),
  ('San Jose de Buenavista', 'Bugarot'),
  ('San Jose de Buenavista', 'Cansadan'),
  ('San Jose de Buenavista', 'Durog'),
  ('San Jose de Buenavista', 'Funda-Dalipe'),
  ('San Jose de Buenavista', 'Igbonglo'),
  ('San Jose de Buenavista', 'Inabasan'),
  ('San Jose de Buenavista', 'Madrangca'),
  ('San Jose de Buenavista', 'Magcalon'),
  ('San Jose de Buenavista', 'Malaiba'),
  ('San Jose de Buenavista', 'Maybato Norte'),
  ('San Jose de Buenavista', 'Maybato Sur'),
  ('San Jose de Buenavista', 'Mojon'),
  ('San Jose de Buenavista', 'Pantao'),
  ('San Jose de Buenavista', 'San Angel'),
  ('San Jose de Buenavista', 'San Fernando'),
  ('San Jose de Buenavista', 'San Pedro'),
  ('San Jose de Buenavista', 'Supa'),
  ('San Remigio', 'Agricula'),
  ('San Remigio', 'Alegria'),
  ('San Remigio', 'Aningalan'),
  ('San Remigio', 'Atabay'),
  ('San Remigio', 'Bagumbayan'),
  ('San Remigio', 'Baladjay'),
  ('San Remigio', 'Banbanan'),
  ('San Remigio', 'Barangbang'),
  ('San Remigio', 'Bawang'),
  ('San Remigio', 'Bugo'),
  ('San Remigio', 'Bulan-bulan'),
  ('San Remigio', 'Cabiawan'),
  ('San Remigio', 'Cabunga-an'),
  ('San Remigio', 'Cadolonan'),
  ('San Remigio', 'Poblacion'),
  ('San Remigio', 'Carawisan I'),
  ('San Remigio', 'Carawisan II'),
  ('San Remigio', 'Carmelo I'),
  ('San Remigio', 'Carmelo II'),
  ('San Remigio', 'General Fullon'),
  ('San Remigio', 'General Luna'),
  ('San Remigio', 'Orquia'),
  ('San Remigio', 'Iguirindon'),
  ('San Remigio', 'Insubuan'),
  ('San Remigio', 'La Union'),
  ('San Remigio', 'Lapak'),
  ('San Remigio', 'Lumpatan'),
  ('San Remigio', 'Magdalena'),
  ('San Remigio', 'Maragubdub'),
  ('San Remigio', 'Nagbangi I'),
  ('San Remigio', 'Nagbangi II'),
  ('San Remigio', 'Nasuli'),
  ('San Remigio', 'Osorio I'),
  ('San Remigio', 'Osorio II'),
  ('San Remigio', 'Panpanan I'),
  ('San Remigio', 'Panpanan II'),
  ('San Remigio', 'Ramon Magsaysay'),
  ('San Remigio', 'Rizal'),
  ('San Remigio', 'San Rafael'),
  ('San Remigio', 'Sinundolan'),
  ('San Remigio', 'Sumaray'),
  ('San Remigio', 'Trinidad'),
  ('San Remigio', 'Tubudan'),
  ('San Remigio', 'Vilvar'),
  ('San Remigio', 'Walker'),
  ('Sebaste', 'Abiera'),
  ('Sebaste', 'Aguila'),
  ('Sebaste', 'Alegre'),
  ('Sebaste', 'Aras-Asan'),
  ('Sebaste', 'Bacalan'),
  ('Sebaste', 'Callan'),
  ('Sebaste', 'Nauhon'),
  ('Sebaste', 'P. Javier'),
  ('Sebaste', 'Poblacion'),
  ('Sebaste', 'Idio'),
  ('Sibalom', 'Alangan'),
  ('Sibalom', 'Valentin Grasparil'),
  ('Sibalom', 'Bari'),
  ('Sibalom', 'Biga-a'),
  ('Sibalom', 'Bongbongan I'),
  ('Sibalom', 'Bongbongan II'),
  ('Sibalom', 'Bongsod'),
  ('Sibalom', 'Bontol'),
  ('Sibalom', 'Bugnay'),
  ('Sibalom', 'Bulalacao'),
  ('Sibalom', 'Cabanbanan'),
  ('Sibalom', 'Cabariuan'),
  ('Sibalom', 'Cabladan'),
  ('Sibalom', 'Cadoldolan'),
  ('Sibalom', 'Calo-oy'),
  ('Sibalom', 'Calog'),
  ('Sibalom', 'Catmon'),
  ('Sibalom', 'Catungan I'),
  ('Sibalom', 'Catungan II'),
  ('Sibalom', 'Catungan III'),
  ('Sibalom', 'Catungan IV'),
  ('Sibalom', 'Cubay-Sermon'),
  ('Sibalom', 'Egaña'),
  ('Sibalom', 'Esperanza I'),
  ('Sibalom', 'Esperanza II'),
  ('Sibalom', 'Esperanza III'),
  ('Sibalom', 'Igcococ'),
  ('Sibalom', 'Igdalaquit'),
  ('Sibalom', 'Igdagmay'),
  ('Sibalom', 'Iglanot'),
  ('Sibalom', 'Igpanolong'),
  ('Sibalom', 'Igparas'),
  ('Sibalom', 'Igsuming'),
  ('Sibalom', 'Ilabas'),
  ('Sibalom', 'Imparayan'),
  ('Sibalom', 'Inabasan'),
  ('Sibalom', 'Indag-an'),
  ('Sibalom', 'Initan'),
  ('Sibalom', 'Insarayan'),
  ('Sibalom', 'Lacaron'),
  ('Sibalom', 'Lagdo'),
  ('Sibalom', 'Lambayagan'),
  ('Sibalom', 'Luna'),
  ('Sibalom', 'Luyang'),
  ('Sibalom', 'Maasin'),
  ('Sibalom', 'Mabini'),
  ('Sibalom', 'Millamena'),
  ('Sibalom', 'Mojon'),
  ('Sibalom', 'Nagdayao'),
  ('Sibalom', 'Cubay-Napultan'),
  ('Sibalom', 'Nazareth'),
  ('Sibalom', 'Odiong'),
  ('Sibalom', 'Olaga'),
  ('Sibalom', 'Pangpang'),
  ('Sibalom', 'Panlagangan'),
  ('Sibalom', 'Pantao'),
  ('Sibalom', 'Pasong'),
  ('Sibalom', 'Pis-Anan'),
  ('Sibalom', 'District I'),
  ('Sibalom', 'District II'),
  ('Sibalom', 'District III'),
  ('Sibalom', 'District IV'),
  ('Sibalom', 'Rombang'),
  ('Sibalom', 'Salvacion'),
  ('Sibalom', 'San Juan'),
  ('Sibalom', 'Sido'),
  ('Sibalom', 'Solong'),
  ('Sibalom', 'Tabongtabong'),
  ('Sibalom', 'Tig-Ohot'),
  ('Sibalom', 'Tigbalua I'),
  ('Sibalom', 'Tordesillas'),
  ('Sibalom', 'Tulatula'),
  ('Sibalom', 'Villafont'),
  ('Sibalom', 'Villahermosa'),
  ('Sibalom', 'Villar'),
  ('Sibalom', 'Tigbalua II'),
  ('Tibiao', 'Alegre'),
  ('Tibiao', 'Amar'),
  ('Tibiao', 'Bandoja'),
  ('Tibiao', 'Castillo'),
  ('Tibiao', 'Esparagoza'),
  ('Tibiao', 'Importante'),
  ('Tibiao', 'La Paz'),
  ('Tibiao', 'Malabor'),
  ('Tibiao', 'Martinez'),
  ('Tibiao', 'Natividad'),
  ('Tibiao', 'Pitac'),
  ('Tibiao', 'Poblacion'),
  ('Tibiao', 'Salazar'),
  ('Tibiao', 'San Francisco Norte'),
  ('Tibiao', 'San Francisco Sur'),
  ('Tibiao', 'San Isidro'),
  ('Tibiao', 'Santa Ana'),
  ('Tibiao', 'Santa Justa'),
  ('Tibiao', 'Santo Rosario'),
  ('Tibiao', 'Tigbaboy'),
  ('Tibiao', 'Tuno')
) as values_to_insert(municipality_name, name)
join public.municipalities on municipalities.name = values_to_insert.municipality_name
on conflict (municipality_id, name) do nothing;
