"use client";

import { useEffect, useRef, useState } from "react";
import "leaflet/dist/leaflet.css";

type IncidentMapProps = { incident: { latitude:number; longitude:number; stationLatitude:number|null; stationLongitude:number|null; stationName:string|null; landmark:string|null } };

export function MunicipalIncidentMap({ incident }: IncidentMapProps) {
  const mapElement = useRef<HTMLDivElement | null>(null); const [routeText,setRouteText]=useState("Calculating road route…");
  useEffect(()=>{let disposed=false; let map: import("leaflet").Map | null=null; (async()=>{const L=await import("leaflet"); if(disposed||!mapElement.current)return; map=L.map(mapElement.current,{zoomControl:true}).setView([incident.latitude,incident.longitude],15); L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(map); const incidentMarker=L.circleMarker([incident.latitude,incident.longitude],{radius:11,color:"#b81711",fillColor:"#e52720",fillOpacity:1,weight:3}).addTo(map).bindPopup(`<b>Incident location</b><br>${incident.landmark||"Resident-reported location"}`); incidentMarker.openPopup(); if(incident.stationLatitude==null||incident.stationLongitude==null){setRouteText("Station coordinates are not set yet. Incident marker is shown.");return;} L.circleMarker([incident.stationLatitude,incident.stationLongitude],{radius:10,color:"#15468a",fillColor:"#2974d8",fillOpacity:1,weight:3}).addTo(map).bindPopup(`<b>${incident.stationName||"BFP Station"}</b>`); const direct:[[number,number],[number,number]]=[[incident.stationLatitude,incident.stationLongitude],[incident.latitude,incident.longitude]]; L.polyline(direct,{color:"#63748b",dashArray:"8 8",weight:3}).addTo(map); map.fitBounds(L.latLngBounds(direct).pad(.25)); try{const q=new URLSearchParams({fromLat:String(incident.stationLatitude),fromLng:String(incident.stationLongitude),toLat:String(incident.latitude),toLng:String(incident.longitude)});const response=await fetch(`/api/routes/road?${q}`);const data=await response.json();const kilometers=Number(data.directKilometers).toFixed(1);if(data.mode==="road"&&Array.isArray(data.coordinates)){L.polyline(data.coordinates,{color:"#d51f18",weight:5,opacity:.9}).addTo(map);setRouteText(`Road route: ${(data.distanceMeters/1000).toFixed(1)} km · about ${Math.max(1,Math.round(data.durationSeconds/60))} min. Direct line: ${kilometers} km.`);}else setRouteText(`Direct line: ${kilometers} km. Road route is temporarily unavailable.`);}catch{setRouteText("Direct line shown. Road route is temporarily unavailable.");}})();return()=>{disposed=true;map?.remove();};},[incident]);
  return <section className="incident-map-card"><div ref={mapElement} className="incident-map" aria-label="Incident route map"/><p className="route-summary">{routeText}</p></section>;
}
