"use client";

import { useEffect, useState } from "react";
import { MunicipalIncidentMap } from "./municipal-incident-map";
import { fireReportStatusLabels, type FireReportStatus } from "../../lib/fire-reports/types";

type Incident = { id:string; referenceNumber:string; status:FireReportStatus; fireType:string; description:string; landmark:string|null; latitude:number; longitude:number; submittedAt:string; responseStartedAt:string|null; respondingStationName:string|null; residentName:string; phone:string; email:string; address:string|null; barangay:string; municipality:string; stationName:string|null; stationLatitude:number|null; stationLongitude:number|null; photos:Array<{url:string|null}>; history:Array<{status:FireReportStatus;message:string|null;createdAt:string}>; previousReports:Array<{id:string;referenceNumber:string;status:FireReportStatus;submittedAt:string}> };

const style=`.incident-shell{padding:1.2rem;max-width:1200px;margin:auto;font-family:Arial,sans-serif;color:#18243a}.incident-header{display:flex;justify-content:space-between;gap:1rem;align-items:flex-start}.incident-header h1{margin:0;font-size:1.45rem}.incident-badge{display:inline-block;margin-top:.35rem;border-radius:999px;padding:.35rem .65rem;background:#fff0ef;color:#bb201a;font-weight:800;font-size:.78rem}.incident-grid{display:grid;grid-template-columns:1.25fr .8fr;gap:1rem;margin-top:1rem}.incident-panel,.incident-map-card{background:#fff;border:1px solid #e5e8ed;border-radius:16px;padding:1rem;box-shadow:0 8px 24px #1520390a}.incident-map{height:360px;border-radius:12px;overflow:hidden}.route-summary{margin:.75rem 0 0;color:#56657b;font-size:.9rem}.respond-button{border:0;border-radius:12px;background:#d9231c;color:white;font-weight:900;padding:.85rem 1rem;cursor:pointer}.respond-button:disabled{opacity:.6}.detail-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem}.detail-list div{background:#f8fafc;border-radius:10px;padding:.7rem}.detail-list span{display:block;color:#6b778b;font-size:.72rem;font-weight:700;text-transform:uppercase}.photo-evidence{width:100%;border-radius:12px;max-height:280px;object-fit:cover;margin-top:.8rem}.history{padding-left:1.1rem;color:#506078}.history li{margin:.5rem 0}@media(max-width:760px){.incident-shell{padding:.75rem}.incident-header{display:block}.respond-button{width:100%;margin-top:.75rem}.incident-grid{grid-template-columns:1fr}.detail-list{grid-template-columns:1fr}.incident-map{height:290px}}`;

export function MunicipalIncidentDetail({ incidentId, onResponded }: { incidentId:string; onResponded?:()=>void }) { const [incident,setIncident]=useState<Incident|null>(null),[error,setError]=useState(""),[sending,setSending]=useState(false); const load=async()=>{const res=await fetch(`/api/municipal-bfp/incidents/${incidentId}`,{cache:"no-store"});const data=await res.json();if(!res.ok)throw new Error(data.error);setIncident(data.incident)}; useEffect(()=>{const timer=window.setTimeout(()=>{load().catch(e=>setError(e.message));},0);return()=>window.clearTimeout(timer);},[incidentId]);const respond=async()=>{setSending(true);setError("");try{const res=await fetch(`/api/municipal-bfp/incidents/${incidentId}/respond`,{method:"POST"});const data=await res.json();if(!res.ok)throw new Error(data.error);await load();onResponded?.();}catch(e){setError(e instanceof Error?e.message:"Unable to start response.")}finally{setSending(false)}}; if(error)return <p className="incident-shell" role="alert">{error}</p>;if(!incident)return <p className="incident-shell">Loading incident…</p>;return <><style>{style}</style><main className="incident-shell"><header className="incident-header"><div><p style={{margin:0,color:"#6a778b"}}>{incident.referenceNumber}</p><h1>{fireReportStatusLabels[incident.status]}</h1><span className="incident-badge">{incident.fireType.replaceAll("_"," ")}</span></div><button className="respond-button" disabled={sending||incident.status==="RESPONDING"} onClick={respond}>{incident.status==="RESPONDING"?"BFP RESPONDING":"RESPOND"}</button></header><div className="incident-grid"><section className="incident-panel"><h2>Resident emergency profile</h2><div className="detail-list"><div><span>Resident</span>{incident.residentName}</div><div><span>Contact</span><a href={`tel:${incident.phone}`}>{incident.phone}</a></div><div><span>Address</span>{incident.address||"Not provided"}</div><div><span>Reported location</span>{incident.barangay}, {incident.municipality}</div><div><span>Landmark</span>{incident.landmark||"Not provided"}</div><div><span>Time reported</span>{new Date(incident.submittedAt).toLocaleString()}</div></div><h2>Incident details</h2><p>{incident.description}</p>{incident.photos[0]?.url&&<img className="photo-evidence" src={incident.photos[0].url} alt="Resident submitted fire evidence"/>}<h2>Status history</h2><ol className="history">{incident.history.map((item,index)=><li key={`${item.createdAt}-${index}`}><b>{fireReportStatusLabels[item.status]}</b> — {item.message||"Updated"}</li>)}</ol></section><MunicipalIncidentMap incident={incident}/></div></main></>}
